### ISSUE TITLE
A multi-threaded callee using a single wampcc session?

### ISSUE THREAD

**Issue by petten** [darrenjs/wampcc#24]
(Note: not really an issue of `wampcc` per se, but exploration of a way of having multiple threads share a `wampcc` session, at app layer.)

Darren, previously I asked you about whether as a callee a `wampcc_session` supported multiple threads. The answer was no.

Now I noticed a `request_id` in the `invocation_info` argument to the callback, and it must be passed as an argument to the eventual `yield()` call that sends the response. Does it mean that as long as I keep track of both the `wampcc_session` reference and the `request_id` for each incoming call, the eventual `yield()` calls sending the respective responses can be out of order?

Individual incoming calls may require different amounts of processing time. The thinking is that the incoming calls can be dispatched to a thread pool through an inbound queue. Those threads do their work and when ready push their respective results into an outbound queue. When the `wampcc` callee's callback logic flow reaches the point of calling `yield()`, it dequeues from the outbound queue (wait until at least one is ready) to send a response, which may or may not correspond to the incoming request during the same call(back).

Furthermore, can we call `yield()` more than once (as long as there are more items in the outbound queue) for a single incoming call(back)?

**Comment by darrenjs** [comment]
> Does it mean that as long as I keep track of both the wampcc_session reference and the request_id for each incoming call, the eventual yield() calls sending the respective responses can be out of order?

Yes, they can be out of order.  That is the purpose of the request_id, to allow caller to match inbound requests to later responses.

Regarding your proposed threading model, I think its fine but I would suggest one change.

You don't need the outbound queue.  When a thread of the thread pool has completed the work of an invocation request, it can call yield itself, rather than push onto the outbound queue.

So the full flow is like this.  When wampcc library receives an invocation message from its peer, its make a call into the user callback function (on the wampcc thread), passing the `invocation_info` argument.  In there you push that request (`invocation_info` & `wamp_session` weak_ptr) onto an inbound queue, and then return.  The wampcc thread can then continue to handle more peer requests inside the library etc.  Meanwhile your worker threads take each queued invocation request, carry out whatever task they have to do, and when ready make a call to either `yield()` or `invocation_error()`. Those calls return immediately, or may throw if the session has closed.

You can call `yield()` more than once, however, the remote caller might not interpret the responses correctly. That is the progressive call feature of WAMP, and wampcc doesn't support it yet.  So I wouldn't recommend doing it.

**Comment by petten** [comment]
Darren, this is awesome!

I'll definitely give it a try when I get a chance.

**Comment by petten** [comment]
Darren, you mentioned that the user should keep the `wamp_session` from the callback argument in a `weak_ptr` until it's time to call `yield()` (need to lock the `weak_ptr` first before making the call, of course).

However, the callback argument type is `wamp_session&` , instead.

Per the `weak_ptr` documentation, one can make a `weak_ptr` from either another `weak_ptr` or a `shared_ptr`. (Though there is a default ctor that can used to make one containing a `nullptr`.)

So how would one make a `weak_ptr<wampcc_session>` from the `wampcc_session&` argument (of the callback)?

The examples in the `weak_ptr` documentation (that I've seen so far) are all made by an assignment from a `shared_ptr`.

**Comment by darrenjs** [comment]
Hi,

The `wamp_session` class inherited from `std::enable_shared_from_this`, so you can just call the inherited method [`shared_from_this`](http://en.cppreference.com/w/cpp/memory/enable_shared_from_this/shared_from_this), or, use helper method` wamp_session::handle`

**Comment by petten** [comment]
OK, thanks!

**Comment by petten** [comment]
Darren, finally I go the chance to try a thread pool.

And exactly as you described above, `wamp_session::yield()` can be called from a thread in the pool, as opposed to the `wampcc` thread that delivered the request in the callback.

Of course, one keeps the `wamp_session` in a `weak_ptr` until the request is processed and response is prepared and ready to go. Then one `lock()`s the `weak_ptr` and makes the `yield()` call on the locked `shared_ptr<wamp_session>`.

As an extra safety measure, I also inserted checking whether the `wamp_session::is_closed()` before invoking `yield()`.

Now my next task would be to add the ability for each `wamp_session` in a pool of them to automatically reconnect to its respective, previously connected to router should the router go offline for a brief period of time (say, maintenance shutdown or an unexpected crash).

It's easier to do it for just a single `wamp_session` in an application; say having a thread simply `wait()` on the `wamp_session::closed_future()`. But for a pool of `wamp_session`s, it'll be a bit more work as the `std` library does not yet have the like of `boost::wait_for_any()`.

**Comment by petten** [comment]
I just realized that one should be able to take advantage of the `on_state_fn` callback passed to `wamp_session::create()`.

Not only does a callback occur upon opening of the `wamp_session`, but another callback also occurs upon closing of the `wamp_session`. Or perhaps in general whenever the state changes of the `wamp_session`.

Since the `on_state_fn()` takes a `wamp_session&` as its first argument, a `weak_ptr` of the `wamp_session` can be made and pushed into a thread-safe queue. On the consumer side of the queue can be one thread (or more) that shall make attempts to reconnect to the router (or recreate the closed `wamp_session`).

What do you think of this approach, Darren?

**Comment by darrenjs** [comment]
Hi,

As for calling `yield()` from the thread pool, that is safe to do, although beware that an exception can be thrown if underlying session socket has already closed.   So catch the exception, and then call close on the `wamp_session` in the catch block.

The `on_state_fn()` is called when the connection has closed (and also if the session does successfully open).   So yes, you can respond to that event, in order to queue a later re-connection attempt.  However,  just to be clear, once a `wamp_session` has closed, it cannot be reopened.  You have to create a brand new `wamp_session`  instance via the `create` method.   For the `wamp_session` that has closed, you just delete it, i.e. reset owning pointers to null.

**Comment by petten** [comment]
Awesome! Many thanks!

Is checking whether `wamp_session::is_closed()` enough before calling `yield()`? Or one must put `yield()` in a `try` block no matter whether `is_closed()` has just been checked or not? Should one also check `wamp_session::is_open()`, as the comment in the code declares that `!is_open()` is not the same as `is_closed()`?

Yes, I noticed that there is not a `reopen()` but only a couple of `create()` functions inside `class wamp_session`. In my case, each `wamp_session` is held in a `std::shared_ptr<wamp_session>`. I think assigning the return value (also a `std::shared_ptr<wamp_session>`) from a `create()` call to the `shared_ptr` holding the closed session should be all right (i.e., displacing/destroying the closed one and replacing it with the newly created).

**Comment by darrenjs** [comment]
Hi,

It is not sufficient to check `is_closed()` before calling `yield()` (or any other send function).

Note that `is_closed()` checks whether the wamp session object is logically closed, i.e., that no more internal callbacks are due into your code.  It is not saying whether the underlying connection is closed;  it is saying "this wamp session object will never make a callback again, so you are safe to delete it".

If `is_closed()` returns true then it does definitely mean that the socket connection is closed, but, if `is_closed()` is false, it doesn't mean the connection is open; it's possible the socket connection has just been lost and the wamp session object is in the process of logically closing.

So while it does no harm to call `is_closed()` before doing a wamp session send, (e.g. a `yield()`),  you should always be ready to handle exceptions thrown ... which just means that the outbound message could not be queued due to the socket connection state.  Just log the event as a warning, and call `close()` on the session.

As for storage of the `wamp_session`, yes, you must use a `std::shared_ptr`.   After the delivery of the on close state callback, you need to reset the smart pointer.  You can either do that explicitly via setting to null,  or yeah, do as in your strategy which is to replace it with a brand new `wamp_session` object if you are able to open a new socket etc.

**Comment by petten** [comment]
> ... you should always be ready to handle exceptions thrown ... which just means that the outbound message could not be queued due to the socket connection state. Just log the event as a warning, and call `close()` on the session.

Additionally as part of the exception handling, after calling `close()` on it, if I'd still like to have the connection to the same router reopened or recreated, it appears this scenario can be treated the same as when the `on_state_fn()` is called back with the argument of `is_open` = `false`. That is, I shall enqueue it for subsequent attempts to recreate the session.

I understand that the logic executed inside a `catch` block must be handled with care. If the overall logic flow forbids a rethrow or another exception being (unexpectedly) thrown from inside a `catch` block, the code in the `catch` block must be enclosed in one (or more) `try` block(s) to prevent it from happening.

**Comment by darrenjs** [comment]
During the exception handling,  lets say you decide to call `session->close()`.  Immediately in the code lines after that, you must not immediately  throw away (i.e. delete) the `wamp_session` instance.    You must only delete the `wamp_session" instance after the `on_state_fn()` is called back with the argument of `is_open = false`.  That's the golden rule.

**Comment by petten** [comment]
I'd like to confirm that my little project was successful of having `wamp_session`s automatically reconnect to temporarily down and then coming back up routers.

Your advice above is greatly appreciated!
